# The URL the site will be built for
base_url = "https://azdevs.github.io/desert-rustaceans"

# Used in RSS by default
title = "Desert Rust"
description = "Phoenix Rust Community"
# The default language, used in RSS
default_language = "en"

theme = "even"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

highlight_theme = "ayu-light"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Whether to generate a RSS feed automatically
generate_rss = true
generate_categories_pages = true
generate_tags_pages = true

taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]


[extra]

even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/tags", name = "Topics"},
    {url = "https://www.meetup.com/Desert-Rustaceans/", name = "Meetup"},
    {url = "https://discord.gg/6SNb2daz", name = "PHX Tech Council Discord #rust"},
    {url = "https://github.com/azdevs/desert-rustaceans", name = "Github"},
]

even_title = "Desert Rust"
